# Generated by Django 3.1.4 on 2021-01-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
