# Generated by Django 3.1.4 on 2021-01-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210113_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Gaming', 'gaming'), ('Housekeeping', 'housekeeping')], default='uncategorised', max_length=100),
        ),
    ]
