# Generated by Django 3.1.4 on 2021-01-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210114_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('gaming', 'Gaming'), ('housekeeping', 'Housekeeping')], default='uncategorised', max_length=100),
        ),
    ]
