# Generated by Django 3.1.4 on 2021-01-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210114_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('gaming', 'Gaming'), ('housekeeping', 'Housekeeping')], max_length=100, null=True),
        ),
    ]
