# Generated by Django 3.1.4 on 2021-01-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210114_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='name_slug',
        ),
    ]
