# Generated by Django 3.1.4 on 2021-01-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20210114_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_slug',
            new_name='slug_name',
        ),
    ]
