# Generated by Django 3.1.4 on 2021-01-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20210115_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='author',
            new_name='user',
        ),
    ]
